forge "http://forge.puppetlabs.com"

mod "puppetlabs/ntp"
mod "puppetlabs/java"
mod "ispavailability/logstash"
mod "thomasvandoren/redis"

mod "nginx",
 :git => "git://github.com/dhutty/puppet-nginx.git"

mod "kibana3",
 :git => "git@github.com:brucem/puppet-kibana3.git"

mod "elasticsearch",
 :git  => "git@github.com:brucem/puppet-elasticsearch.git"




