forge "http://forge.puppetlabs.com"

mod "puppetlabs/ntp"
mod "puppetlabs/java"
mod "ispavailability/logstash"
mod "thomasvandoren/redis"

mod "elasticsearch",
 :git  => "git@github.com:brucem/puppet-elasticsearch.git"

#mod "garethr/kibana"

mod "kibana",
 :git  => "git@github.com:brucem/garethr-kibana.git"


